### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by farkas1070** [Teaching-projects/SOE-ProgAlap1-Beadando-Simon-Marton#1]
Issue opened

**Comment by hegyhati** [comment]
Sok megjegyzesem van, de kezdem azzal, hogy szuper a dolog, tetszik, es ezzel a felhanggal tessek a tobbit olvasni.

`main.py`
- [x] json-t nem hasznalod semmire
- [x] erre a fuggvenyre semmi szukseg nincsen, nyugodtan hivd csak meg a `game.main()`-t

`game.py`
- [x] l9: "saves in" -> "loads" gondolom
- [x] l14: tudom, megeszi, de foleg generalt fajlokban ekezetes karaktereket haznalni nem szep.
- [x] l15: ez akkor nem csak generalja a mapot,hanem ki is irja, illetve generalast nem is latok, csak betoltest.
- [x] A 4 iranyhoz tartozo fuggvenyek szinte mind ugyanazok , 1-2 elteres van csak bennuk, ezt a redundanciat jo volna kiirtani.


`alapok.py`
- [x] szuper, hogy vannak tesztjeid, de ezeket tedd bele a docstringbe ugy, ahogy az oran neztuk, hogy lefuttathatoak legyenek.
- [x] l36-41 ez a fuggveny ok, de kicist egyszerusitheto. Mondhatnank csak annyit, hogy 1x generaljuk random, aztan amig nem jo, addig generaljuk ujra. (if-eles nem kell). 
- [x] l55: itt valamiert nem adtal visszateresi erteket a def soraban, aztan a docstringben azt irod, hogy nincs, aztan megiscsak van egy return map.
- [x] ugyanennel a fuggvenynel. Itt keveredik az elso map generalasa, valamint a UI kiirasa. Ezek kulonvalasztandoak. Meg nem ertem a vegere, de valoszinuleg az "alapok" lenne a jo hely mindnre, ami logika, es a game pedig mindenre ami felhasznaloi interakcio.
- [x] horizontal_move_exists: akkor is letezik, ha valahol 0 van, es oda tudunk csusztatni. Amikor jatszottam, akkor ez jol mukodott, szoval gondolom valahol tesztelve van, csak nem itt, Viszont akkor vagy itt kellene, vagy at kell irni a nevet, leirasat, mert nem azt csinalja, amit mond magarol. Valoszinuleg utobbi, mert itt horizontal van csak, nincs kulon jobbra/balra, (fuggolegesnel ugyanez), szoval ez tenyleg csak annyit mond, hogy horizontalisan van-e merge lehetoseg.
- [x] lose: a 0-k megszamolasat en lehet kitennem egy fuggvenybe es akkor ez egy sor lenne, egy return, ahol 3 tagot eselek. Na, van is vanenulla fuggvenyed.
- [x] ugyanit a `FOO==False` helyett lehet `not FOO`-t irni, ami rovidebb, es konnyebben is olvashato
- [x] A fuggvenyneveid legyenek konzisztensek. Ertem ez alatt, hogy vagy legyen mind magyar, vagy mind angol, es `isitok`, `isItOk`, `is_it_ok`, `is-it-ok` stb kozul tessek egy stilust valasztani, es ahhoz tartani Magad.
- [x] osszehuzas: ha jol ertem, ez annyit csinal, hogy a new map ugyanaz mint a map, sak a 0-k ki vannak szorva. Ez a leirasbol annyira nem jon at (persze ha a pelda rendesen itt lenne, lasd fentebb,az segitene.)
- [x] Az osszeges ha jol latom, csak vizszintesen osszegez, es mindig balra. Ezeket a fuggvenyeket amugy lehet csak 1 sorra irnam meg, mivel a sorok egymastol tok fuggetlenek, es a for i in range... lehetne ott is, ahol meghivom, az osszevonas, stb logikaja meg akkor jobban atjonne itt.
- [x] l251: akar hasznalhatnal negativ indexeket is, de igy is rendbn van. 
- [x] mapforditas: ezt transzponalasnak hivjak, a sorvaltast meg talan lehetne tukrozesnek.
- [x] mentes/betoltes/getcommand -> tipikusan a game-be menjen, mar csak azert is, mert itt a score.


`scoring.py`
- [x] a writescore-nak felesleges megkapni a score-t, inkabb hivja meg O a map-re a score fv-t. Ugyanakkor, mivel ez is UI,en ezt is a game-be tennem.  A maradek egy fuggvenynek meg kulon file-t csinalni overkillnek tunik. Valoszinuleg az alapokba tennem at.

**Comment by farkas1070** [comment]
Kijavítottam mindent, mindjárt ujragenerálom a dokumentációkat, és felpusholok mindent!

**Comment by farkas1070** [comment]
minden fel van pusholva

**Comment by hegyhati** [comment]
Szia! MEgneztem, vannak dolgok, amik nem okesak meg. Jelenleg ez 4-esen all, de en szeretnek 5-ot adni. De hogy mi valaszt el tole, azt egyszerubb lenne most mar szoban atbeszelni. Holnap vizsga idopontjaban felhivlak Teams-en.

**Comment by farkas1070** [comment]
remélem nem hagytam ki semmit azokból amit megbeszéltünk, a docstringek működnek, mindehol ahol tudtam egyszerűsítettem, szétszedtem sorokra a pull és merge függvényeket, a 0-ás dolgot megbsezéltük, jobb neveket adtam stb...

    kiszedtem azokat a global változókat, beirtam a file-nevét a save-függvénybe, a get_commandos függvényt is kitöröltem, és helyette másként oldottam meg

**Comment by hegyhati** [comment]
Szia! Rendben van, irom be az otost, a readme-t majd meg kicist pimpeld meg screenshotokkal, vagy barmi :-)
